import fs from "node:fs";
import path from "node:path";

function lcg(seed) {
  let state = seed >>> 0;
  return () => {
    state = (1664525 * state + 1013904223) >>> 0;
    return state / 2 ** 32;
  };
}

function fmt(x) {
  return Number.isFinite(x) ? x.toFixed(6) : String(x);
}

const rng = lcg(0);
const nRows = 100;

function randn() {
  // Box–Muller transform using the seeded LCG.
  // Avoid u=0 which would produce -Infinity in log.
  let u = rng();
  let v = rng();
  if (u <= 0) u = 1e-12;
  if (v <= 0) v = 1e-12;
  return Math.sqrt(-2.0 * Math.log(u)) * Math.cos(2.0 * Math.PI * v);
}

const header = ["x0", "x1", "y"];
const lines = [header.join(",")];

for (let i = 0; i < nRows; i++) {
  const x0 = 2.0 * randn();
  const x1 = 2.0 * randn();
  const y = 2.0 * Math.cos(x0) + x1 * x1 - 2.0;
  lines.push([fmt(x0), fmt(x1), fmt(y)].join(","));
}

const csv = lines.join("\n") + "\n";

const outPath = path.join(process.cwd(), "src", "generated", "defaultCsv.ts");
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(
  outPath,
  `// AUTO-GENERATED by scripts/generate_default_csv.mjs\n// x0, x1 ~ 2*randn(); Formula: y = 2*cos(x0) + x1^2 - 2\n\nexport const DEFAULT_CSV: string = ${JSON.stringify(
    csv
  )};\n`
);
